baseURL = "https://akhmad.id/blog/"
languageCode = "id-id"
defaultContentLanguage = "id"
title = "Akhmad"
theme = "akhmad"

[params]
    description = "Cerita, Catatan, dan tulisan untuk mendokumentasikan sesuatu."