name: Update blog posts
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v2
      - name: Setup node v15
        uses: actions/setup-node@v1
        with: 
          node-version: '15'
      - name: TailwindCSS build production
        run: |
          yarn install
          yarn prod
        working-directory: ./themes/akhmad/src
      - name: Deploy to gh-pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.79.0
          GITHUB_ACTOR: octocat
          TARGET_REPO: rockavoldy/blog
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}